### ISSUE TITLE
1.0.3 version tag moved from its original commit

### ISSUE THREAD

**Issue by godrei** [mcaldas/bitrise-step-telegram-notify#2]
Hi, it seems you shared the step's `6799db07780e5907f0a30646ba7a65663ed8abc5` state with tag: `1.0.3` into the steplib: https://github.com/bitrise-io/bitrise-steplib/pull/1788/files, but currently the tag is on different commit: `623cc5ad9d9b0fd632e02e1c672b1eaecfa52dc0`.

Please move the tag back to the original commit as we use the original commit to validate that a step version always means the same state of the step.

This is the first item in our StepLib's New Pull Request Checklist: `I will not move an already shared step version's tag to another commit`

**Comment by mcaldas** [comment]
@godrei  actually i moved the tag when i updated the PR (before it was approved), anyway, moved it back now.

**Comment by godrei** [comment]
@mcaldas thanks for the update, now the steplib works well and you should see the new step version,
